name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout sin credenciales persistentes
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Instala Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Instala dependencias
      - name: Install dependencies
        run: pip install mkdocs-material

      # Build del sitio
      - name: Build site
        run: mkdocs build

      # Deploy a gh-pages
      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          cd site
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Deploy MkDocs site"
          git branch -M gh-pages
          git remote add origin https://$GH_TOKEN@github.com/$REPO.git
          git push origin gh-pages --force
